[versions]
minecraft = "1.21.1"
yarn = "1.21.1+build.3"
fabric-api = "0.105.0+1.21.1"
fabric-loader = "0.16.5"
kotlin = "2.0.20"
fabric-language-kotlin = "1.12.2+kotlin.2.0.20"
loom = "1.7-SNAPSHOT"
coroutines = "1.9.0"
slf4j = "2.0.13"
koin = "3.5.6"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin"}

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "loom" }