name: 🐛 | 提交BUG-zh_tw
description: 🎤 | 提交您在TouchController中發現的BUG
title: "[BUG]: "
labels: ["BUG"]
body:
- type: markdown
  attributes:
    value: "# 🎁 | 歡迎填寫TouchController BUG反饋!"
- type: checkboxes
  id: BUG_Prefeedback
  attributes:
    label: 檢查項目
    description: 在提交前，請確認以下內容：
    options:
      - label: 此BUG尚未被提交過（可在[這裡](https://github.com/fifth-light/TouchController/issues?q=is%3Aissue)進行搜尋）
        required: true
      - label: 此BUG的修復不在[PR](https://github.com/fifth-light/TouchController/pulls)中
        required: true
      - label: 我已將模組更新到最新版本
        required: true
      - label: 我使用了修改版安卓啟動器，且為最新版本
        required: false
      - label: 我已了解：若使用不受支援的作業系統所產生的任何問題，均不可在此提交（如需支援某作業系統，請前往提交新功能）
        required: true
- type: dropdown
  id: BUGInTouchController_OS
  attributes:
    label: 作業系統
    description: 您使用的作業系統，若選擇「其他」，請在下文中說明
    options:
      - Android
      - Windows
      - Mac OS
      - Linux
      - other
    default: 1
  validations:
    required: true
- type: input
  id: Verison
  attributes:
    label: 版本
    description: 您發現此BUG時所使用的模組版本、Minecraft版本以及加載器
    placeholder: 模組版本：vx.x.x；Minecraft版本：x.x.x；模組加載器：***
  validations:
    required: true
- type: textarea
  id: BUGInMSS3_Retry
  attributes:
    label: 重現步驟
    description: 請簡要說明如何觸發這個BUG
    placeholder: |
      1. xxx
      2. xxx
      3. xxx
  validations:
    required: true
- type: textarea
  id: UploadLog
  attributes:
    label: 日志
    description: 上傳您的啟動器日志以及遊戲日志（通常位於`.minecraft\versions\<版本文件夾>\logs`中）
  validations:
    required: true
- type: markdown
  attributes:
    value: "### 🎉 | 感謝您對TouchController的支持!" 