modLoader = "javafml"
loaderVersion = "[4.11,)"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "fifth_light, bukeyu"
description = "${mod_description}"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${game_version}"
ordering = "NONE"
side = "CLIENT"
