# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [ pull_request, push ]

jobs:
    build:
        strategy:
            matrix:
                # Use these Java versions
                java: [
                    21,    # Current Java LTS
                ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Setup JDK ${{ matrix.java }}
                uses: actions/setup-java@v4
                with:
                    java-version: ${{ matrix.java }}
                    distribution: 'temurin'
                    cache: 'gradle'
            -   name: Setup Rust
                uses: actions-rust-lang/setup-rust-toolchain@v1
                with:
                    target: 'i686-pc-windows-gnu, x86_64-pc-windows-gnu, armv7-linux-androideabi, aarch64-linux-android, i686-linux-android, x86_64-linux-android'
            -   name: Setup MinGW GCC
                run: sudo apt-get install -y gcc-mingw-w64-i686 gcc-mingw-w64-x86-64
            -   name: Setup Android SDK
                uses: android-actions/setup-android@v3
            -   name: Setup Android NDK
                uses: nttld/setup-ndk@v1
                with:
                    ndk-version: r27c
                    link-to-sdk: true
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Install cargo-ndk
                run: cargo install cargo-ndk
            -   name: Build
                run: ./gradlew build --no-daemon
            -   name: Capture build artifacts
                if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
                uses: actions/upload-artifact@v4
                with:
                    name: Artifacts
                    path: mod/build/libs/
